name: geofdn

mast3r_backbone:
  pos_embed: 'RoPE100'
  patch_embed_cls: 'PatchEmbedDust3R'
  img_size: [320, 480]
  head_type: 'gaussian_head'
  output_mode: 'pts3d+gaussian+desc24'
  enc_embed_dim: 1024
  enc_depth: 24
  enc_num_heads: 16
  dec_embed_dim: 768
  dec_depth: 12
  dec_num_heads: 12
  two_confs: True
  use_offsets: True
  pretrained_mast3r_path: './checkpoints/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth'

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1
  
num_surfaces: 1

gaussians_per_pixel: 1

gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 4

visualizer:
  num_samples: 8
  min_resolution: 256
  export_ply: false
  
downscale_factor: 4
shim_patch_size: 4

# below are ablation settings, keep them as false for default model
wo_depthpos: false  
wo_depthenc: false   

