defaults:
  - dataset: waymo
  - model/encoder: geofdn
  - model/decoder: splatting_cuda
  - loss: [mse]

wandb:
  project: geo-foundation
  entity: 
  name: placeholder
  mode: disabled
  id: null

mode: train

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 10
    batch_size: 1
    seed: 1234
  test:
    num_workers: 1
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    batch_size: 1
    seed: 3456

optimizer:
  lr: 1.e-4
  warm_up_steps: 2000
  cosine_lr: true

checkpointing:
  load: null
  every_n_train_steps: 10000 
  save_top_k: -1
  pretrained_model: null

train:
  depth_mode: null
  extended_visualization: false
  print_log_every_n_steps: 100

test:
  output_path: outputs/test
  compute_scores: true
  crop_range_h: [6, 6]
  crop_range_w: [10, 6]
  eval_time_skip_steps: 0
  save_image: true
  save_video: true
  lane_shift: true
  lane_shift_step: 1

seed: 111123

trainer:
  max_steps: -1
  val_check_interval: 1.0
  gradient_clip_val: 0.5
  num_sanity_val_steps: 2

output_dir: null
